name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  
jobs:
  validate:
    uses: Tieqiong/diffpyworkflow/.github/workflows/re_main.yml@main
    with:
      project: PROJECT_NAME
      c_extension: false
      headless: false
