name: Gather coverage report and upload to codecov

on:
  push:
    branches:
      - main
  release:
    types:
      - prereleased
      - published
  workflow_dispatch:

env:
  project: diffpy.workflow
  c_extension: false
  headless: false

jobs:
  coverage:
    uses: Tieqiong/diffpyworkflow/.github/workflows/re_codecov.yml@main
    with:
      project: ${{ env.project }}
      c_extension: ${{ env.c_extension }}
      headless: ${{ env.headless }}
