name: Gather coverage report and upload to codecov

on:
  push:
    branches:
      - main
  release:
    types:
      - prereleased
      - published
  workflow_dispatch: null

jobs:
  coverage:
    uses: Tieqiong/diffpyworkflow/.github/workflows/re_codecov.yml@main
    with:
      project: diffpy.workflow
      c_extension: false
      headless: false
