name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

jobs:
  validate:
    uses: Tieqiong/diffpyworkflow/.github/workflows/re_main.yml@main
